#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metalevel.maude -no-banner -no-advise \
  > metalevel.out 2>&1

diff $srcdir/metalevel.expected metalevel.out > /dev/null 2>&1
