#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/parameterization.maude -no-banner -no-advise \
  > parameterization.out 2>&1

diff $srcdir/parameterization.expected parameterization.out > /dev/null 2>&1
