#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/assocUnification.maude -no-banner -no-advise \
  > assocUnification.out 2>&1

diff $srcdir/assocUnification.expected assocUnification.out > /dev/null 2>&1
