#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/attributes.maude -no-banner -no-advise \
  > attributes.out 2>&1

diff $srcdir/attributes.expected attributes.out > /dev/null 2>&1
