#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/continue.maude -no-banner -no-advise \
  > continue.out 2>&1

diff $srcdir/continue.expected continue.out > /dev/null 2>&1
