#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/dataStructures.maude -no-banner -no-advise \
  > dataStructures.out 2>&1

diff $srcdir/dataStructures.expected dataStructures.out > /dev/null 2>&1
