#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/diophantine.maude -no-banner -no-advise \
  > diophantine.out 2>&1

diff $srcdir/diophantine.expected diophantine.out > /dev/null 2>&1
