#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/parameterizedView.maude -no-banner -no-advise \
  > parameterizedView.out 2>&1

diff $srcdir/parameterizedView.expected parameterizedView.out > /dev/null 2>&1
