#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/renaming.maude -no-banner -no-advise \
  > renaming.out 2>&1

diff $srcdir/renaming.expected renaming.out > /dev/null 2>&1
