#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/rot13.maude -no-banner -no-advise \
  > rot13.out 2>&1

diff $srcdir/rot13.expected rot13.out > /dev/null 2>&1
