#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/variantUnification.maude -no-banner -no-advise \
  > variantUnification.out 2>&1

diff $srcdir/variantUnification.expected variantUnification.out > /dev/null 2>&1
