#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/view.maude -no-banner -no-advise \
  > view.out 2>&1

diff $srcdir/view.expected view.out > /dev/null 2>&1
