#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/legacyMetaUnify.maude -no-banner -no-advise \
  > legacyMetaUnify.out 2>&1

diff $srcdir/legacyMetaUnify.expected legacyMetaUnify.out > /dev/null 2>&1
