#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaIntUnify.maude -no-banner -no-advise \
  > metaIntUnify.out 2>&1

diff $srcdir/metaIntUnify.expected metaIntUnify.out > /dev/null 2>&1
