#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaUpModExp.maude -no-banner -no-advise \
  > metaUpModExp.out 2>&1

diff $srcdir/metaUpModExp.expected metaUpModExp.out > /dev/null 2>&1
