#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaRewrite.maude -no-banner -no-advise \
  > metaRewrite.out 2>&1

diff $srcdir/metaRewrite.expected metaRewrite.out > /dev/null 2>&1
