#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaNarrow.maude -no-banner -no-advise \
  > metaNarrow.out 2>&1

diff $srcdir/metaNarrow.expected metaNarrow.out > /dev/null 2>&1
