#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaMeta.maude -no-banner -no-advise \
  > metaMeta.out 2>&1

diff $srcdir/metaMeta.expected metaMeta.out > /dev/null 2>&1
