#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaXapply.maude -no-banner -no-advise \
  > metaXapply.out  2>&1

diff $srcdir/metaXapply.expected metaXapply.out > /dev/null 2>&1
