#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaXmatch.maude -no-banner -no-advise \
  > metaXmatch.out 2>&1

diff $srcdir/metaXmatch.expected metaXmatch.out > /dev/null 2>&1
