#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaTerm.maude -no-banner -no-advise \
  > metaTerm.out 2>&1

diff $srcdir/metaTerm.expected metaTerm.out > /dev/null 2>&1
