#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaParse.maude -no-banner -no-advise \
  > metaParse.out 2>&1

diff $srcdir/metaParse.expected metaParse.out > /dev/null 2>&1
