#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaPrettyPrint.maude -no-banner -no-advise \
  > metaPrettyPrint.out 2>&1

diff $srcdir/metaPrettyPrint.expected metaPrettyPrint.out > /dev/null 2>&1
