#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaModExp.maude -no-banner -no-advise \
  > metaModExp.out 2>&1

diff $srcdir/metaModExp.expected metaModExp.out > /dev/null 2>&1
