#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaVariantUnify.maude -no-banner -no-advise \
  > metaVariantUnify.out 2>&1

diff $srcdir/metaVariantUnify.expected metaVariantUnify.out > /dev/null 2>&1
