#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaUpDown.maude -no-banner -no-advise \
  > metaUpDown.out 2>&1

diff $srcdir/metaUpDown.expected metaUpDown.out > /dev/null 2>&1
