#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaMatch.maude -no-banner -no-advise \
  > metaMatch.out 2>&1

diff $srcdir/metaMatch.expected metaMatch.out > /dev/null 2>&1
