#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/russianDollsNonFlat2.maude -no-banner -no-advise \
  > russianDollsNonFlat2.out 2>&1

diff $srcdir/russianDollsNonFlat2.expected russianDollsNonFlat2.out > /dev/null 2>&1
