#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/metaIntRewriteJune2018.maude -no-banner -no-advise \
  > metaIntRewriteJune2018.out 2>&1

diff $srcdir/metaIntRewriteJune2018.expected metaIntRewriteJune2018.out > /dev/null 2>&1
