#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/polymorphicOverloadMay2019.maude -no-banner -no-advise \
  > polymorphicOverloadMay2019.out 2>&1

diff $srcdir/polymorphicOverloadMay2019.expected polymorphicOverloadMay2019.out > /dev/null 2>&1
