#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/staleViewJune2018.maude -no-banner -no-advise \
  > staleViewJune2018.out 2>&1

diff $srcdir/staleViewJune2018.expected staleViewJune2018.out > /dev/null 2>&1
