#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/viewRecursionMay2019.maude -no-banner -no-advise \
  > viewRecursionMay2019.out 2>&1

diff $srcdir/viewRecursionMay2019.expected viewRecursionMay2019.out > /dev/null 2>&1
