#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/counters.maude -no-banner -no-advise \
  > counters.out 2>&1

diff $srcdir/counters.expected counters.out > /dev/null 2>&1
