#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/int.maude -no-banner -no-advise \
  > int.out 2>&1

diff $srcdir/int.expected int.out > /dev/null 2>&1
