#!/bin/sh

MAUDEV_LIB=$srcdir/../../src/Main
export MAUDEV_LIB

../../src/Main/maude \
  < $srcdir/rat.maude -no-banner -no-advise \
  > rat.out 2>&1

diff $srcdir/rat.expected rat.out > /dev/null 2>&1
